name: Test

on:
  push:

jobs:
  testgo:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.1"
          cache: true

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=10m ./...
